### ISSUE TITLE
doing !chat just writes it in chat

### ISSUE THREAD

**Issue by Netherite2** [Jacobwasbeast/Minecraft-AI-ChatBot#4]
What the title says

**Comment by Jacobwasbeast** [comment]
Do  you have the mod installed in your current instance of the game?

**Comment by pseudoforceyt** [comment]
can replicate, Minecraft Java 1.17 Java SE 16.0.1+9 Fabric 0.11.3
![image](https://user-images.githubusercontent.com/70620481/121365549-6099e180-c956-11eb-8905-94787c8e08a3.png)
Mods installed:
Ai Chatbot
many of Giselbaer's mods
Fabric API
Bedrockify
Optifabric
![image](https://user-images.githubusercontent.com/70620481/121365908-abb3f480-c956-11eb-84cb-7e86c1cbdb14.png)
not working in survival singleplayer too

**Comment by Jacobwasbeast** [comment]
Sorry I was slow I will get working on a fix.

**Comment by Netherite2** [comment]
heres my mod list: 
![image](https://user-images.githubusercontent.com/77221236/123903612-a57ccb00-d98c-11eb-874f-9d87d79fd864.png)
![image](https://user-images.githubusercontent.com/77221236/123903682-c6452080-d98c-11eb-8554-be5039eb502f.png)

**Comment by Jacobwasbeast** [comment]
Creating new version using GPT3 should be out in a couple days.
